CONTROLNET_CANNY_URL = "https://api.segmind.com/v1/sd1.5-controlnet-canny"

PARAGON_URL = "https://api.segmind.com/v1/sd1.5-paragon"

STABLE_DIFFUSION_URL = "https://api.segmind.com/v1/sdxl1.0-txt2img"

STABLE_DIFFUSION_NEGAVTIVE_PROMPT = "ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, extra limbs, disfigured, deformed, body out of frame, blurry, bad anatomy, blurred, watermark, grainy, signature, cut off, draft"
STABLE_DIFFUSION_RETRY_COUNT = 5
STABLE_DIFFUSION_STYLES = [
    "base",
    "3d-model",
    "analog film",
    "anime",
    "cinematic",
    "comic book",
    "craft clay",
    "digital art",
    "enhance",
    "fantasy art",
    "isometric",
    "line art",
    "lowpoly",
    "neonpunk",
    "origami",
    "photographic",
    "pixel art",
    "texture",
    "advertising",
    "automotive",
    "corporate",
    "fashion editorial",
    "food photography",
    "luxury",
    "real estate",
    "retail",
    "abstract",
    "abstract expressionism",
    "art deco",
    "art nouveau",
    "constructivist",
    "cubist",
    "expressionist",
    "graffiti",
    "hyperrealism",
    "impressionist",
    "pointillism",
    "pop art",
    "psychedelic",
    "renaissance",
    "steampunk",
    "surrealist",
    "typography",
    "watercolor",
    "futuristic-biomechanical",
    "futuristic-biomechanical cyberpunk",
    "futuristic-cybernetic",
    "futuristic-cybernetic robot",
    "futuristic-cyberpunk cityscape",
    "futuristic-futuristic",
    "futuristic-retro cyberpunk",
    "futuristic-retro futurism",
    "futuristic-sci-fi",
    "futuristic-vaporwave",
    "bubble bobble",
    "cyberpunk game",
    "fighting game",
    "gta",
    "mario",
    "minecraft",
    "pokemon",
    "retro arcade",
    "retro game",
    "rpg fantasy game",
    "strategy game",
    "streetfighter",
    "zelda",
    "architectural",
    "disco",
    "dreamscape",
    "dystopian",
    "fairy tale",
    "gothic",
    "grunge",
    "horror",
    "kawaii",
    "lovecraftian",
    "macabre",
    "manga",
    "metropolis",
    "minimalist",
    "monochrome",
    "nautical",
    "space",
    "stained glass",
    "techwear fashion",
    "tribal",
    "zentangle",
    "collage",
    "flat papercut",
    "kirigami",
    "paper mache",
    "paper quilling",
    "papercut collage",
    "papercut shadow box",
    "stacked papercut",
    "thick layered papercut",
    "alien",
    "film noir",
    "hdr",
    "long exposure",
    "neon noir",
    "silhouette",
    "tilt-shift",
]
