STABLE_DIFFUSION_PROMPT_GEN_PARAMS = {
    "medium": [
        "image",
        "photograph",
        "headshot",
        "painting",
        "depiction",
        "cartoon",
        "drawing",
        "figure",
        "illustration",
        "sketch",
        "portrait",
        "digital painting",
        "concept art",
        "scene",
        "digital art",
        "render",
        "oil painting",
        "anime drawing",
        "polaroid",
        "visual art",
        "close-up",
        "landscape",
        "panoramic",
        "idyllic",
    ],
    "style": [
        "hyperrealistic",
        "Modernist",
        "Abstract",
        "Impressionist",
        "Expressionist",
        "Surrealist",
        "fantasy",
        "Photorealism",
        "pop-art",
        "art deco",
        "rococo",
        "art nouveau",
    ],
    "artist": [
        "Vincent van Gogh",
        "Pablo Picasso",
        "Andrew Warhol",
        "Frida Kahlo",
        "Jackson Pollock",
        "Salvador Dali",
        "Android Jones",
        "Kilian Eng",
        "Huang Guangjian",
        "Stanley Artgerm Lau",
        "Brad Rigney",
        "Tooth Wu",
        "Otto Dix",
        "Zdzisław Beksiński",
        "Tep Sitha",
        "John Collier",
        "Krenz Cushart",
        "Ross Tran",
    ],
    "website": [
        "ArtStation",
        "DeviantArt",
        "pixabay",
        "iStock",
        "cgsociety",
        "pixiv",
    ],
    "resolution": [
        "4k",
        "8k",
        "HD",
        "pixelated low res",
        "highly detailed",
        "Canon50",
        "octane render",
        "absurdly detailed",
        "unreal engine",
        "vray",
        "houdini render",
        "sharp focus",
        "soft focus",
    ],
    "details": [
        "detailed",
        "smooth",
        "stunningly beautiful",
        "extremely detailed face",
        "bokeh",
        "intricate",
        "heavenly",
        "beautiful",
        "surreal",
        "natural lighting",
        "epic",
        "ornate",
        "expansive",
        "diffuse lighting",
        "Organic",
        "lifelike",
        "low angle shot",
        "intricate design",
        "cinematic lighting",
        "silk",
        "seductive",
        "Symmetric face",
        "Cinematic",
        "dramatic",
        "sci-fi",
        "lush detail",
        "Crystalline",
        "hard shadows",
        "luminescence",
        "translucent",
    ],
    "color": [
        "enamelled",
        "colorful",
        "iridescent gold",
        "iridescent accents",
        "vibrant color",
        "silver",
        "vivid",
        "ektachrome",
        "muted colors",
        "color grading",
        "tone mapping",
        "vintage",
        "aesthetic",
    ],
}
